setwd("/Users/kristen/Dropbox/AndersenLab/LabFolders/Kristen/TEPaper/recent")

load("line2a.Rda")
unique(line2a$gene_name)
load("cer4.Rda")
unique(cer4$gene_name)
load("cer8.Rda")
unique(cer8$gene_name)
load("mirage1.Rda")	
unique(mirage1$gene_name)
load("tc1.Rda") 
unique(tc1$gene_name)
load("wb046.Rda")
unique(wb046$gene_name)

load("total_retro_abs.Rda")
unique(total_retro_abs$gene_name)
load("total_retro_ref.Rda")	
unique(total_retro_ref$gene_name)
load("total_dna_abs.Rda")
unique(total_dna_abs$gene_name)
load("total_dna_ins.Rda")
unique(total_dna_ins$gene_name)
load("total_dna_ref.Rda")
unique(total_dna_ref$gene_name)

load("rares.Rda")
length(unique(rares$strain))
length(unique(rares$gene_id))
