---
output: pdf_document
geometry: margin=.5in
mainfont: "Helvetica"
---




```{r,warning=F, message=F, echo=F, comment=NA}

#print a table of:
#1) peaks, 
#2) their positions, 
#3) the variance explained for that QTL, 
#4) and the left and right confidence intervals


library(dplyr)
library(data.table)
library(reshape2)
library(stringr)
library(ggplot2)
library(tidyr)
library(stargazer)

load("/Users/kristen/Documents/transposon_figure_data/data/Processed_Transposon_Mappings.Rda") #processed mappings

```



```{r,warning=F, message=F, echo=F, comment=NA}

#remove fraction and movement traits
processed_mapping_df<-subset(processed_mapping_df,
                                 grepl('^I', processed_mapping_df$trait) |
                                   grepl('^V', processed_mapping_df$trait) |
                                   grepl('^X', processed_mapping_df$trait)|
                                   grepl('_C$', processed_mapping_df$trait))
processed_mapping_df<-subset(processed_mapping_df,!grepl('^no_', processed_mapping_df$trait))

#remove "TRANS" from transposon names
processed_mapping_df$trait <- gsub("_TRANS_" ,"_",processed_mapping_df$trait)

#transposon <- stringr::str_split_fixed(processed_mapping_df$trait, "_TRANS_",2)[,2]
#caller <- stringr::str_split_fixed(processed_mapping_df$trait, "_TRANS_",2)[,1]
#processed_mapping_df$trait <-paste(caller,transposon,sep="_")
```


```{r,warning=F, message=F, echo=F, comment=NA}
#print table
# write out table of info on each unique peak
peaks <- filter(processed_mapping_df, !is.na(peak_id))
peaks <- filter(peaks, !is.na(allele))
#pull unique combinations of trait and peak id
sites_clean <- distinct(peaks, peak_id, trait)
table_info<-select(sites_clean, trait,peak_id,CHROM,POS,var.exp,startPOS,endPOS)   
colnames(table_info) <- c("Trait", "PeakID","Chromosome","BasePosition", "VarianceExplained(%)", "LeftCI", "RightCI")
table_info<-format(table_info, digits = 3)
stargazer(table_info,type='text',font.size="tiny",summary=FALSE)
?stargazer
```


