library(ape)
setwd("/Users/kristen/Documents/transposon_figure_data/data")
input<-read.table("kin_matrix_full.txt")
as.dist(input)
njs(input)
m <- as.matrix(read.table("kin_matrix_full.txt", head=T, row.names=1)) 
arbol <- nj(as.dist(m))
print(m)
as.dist(m)
